# User test config  (YAML format)
# 
# Add sections to override the default

# If problems with format try: http://yaml-online-parser.appspot.com

# this should work
HW-pass:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  results:
        epilog_script: 'iPassed'

# this should fail 
HW-noFound:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  results:
        epilog_script: 'dummy'

# this should work
HW-pass-relative:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  results:
        epilog_script: './iPassed'

# this should fail 
HW-notExec:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  results:
        epilog_script: './notExec'

# this should work
HW-pass-abs:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  results:
        epilog_script: '/Users/cwi/VWE/PAV/iPassed'
