# User test config  (YAML format)
# 
# Add sections to override the default

# If problems with format try: http://yaml-online-parser.appspot.com

HW-moab1:
  source_location: '/Users/cwi/VWE/t1'
  run:
    cmd: 'hwMoab.bash'
    scheduler: moab 
  moab:
    target_seg: 'mu'
    num_nodes: '1'

HW-moab2:
  source_location: '/Users/cwi/VWE/t1'
  run:
    cmd: 'hwMoab.bash'
    scheduler: moab 
  moab:
    target_seg: 'mu'
    num_nodes: '1,2'
