# User test config  (YAML format)
# 
# Add sections to override the default

# If problems with format try: http://yaml-online-parser.appspot.com

HW-raw-1:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path:

HW-raw-2:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: './myws'

HW-raw-3:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: '/'

HW-raw-4:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: '/tmp'

HW-raw-5:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: '/tmp'

HW-raw-6:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: 'tmp'

HW-raw-7:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: 'NO-WS'

HW-moab:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: moab 
  build:
    build_before_run_flag: True
