# User test config  (YAML format)
# 
# Add sections to override the default

# If problems with format try: http://yaml-online-parser.appspot.com

simple-1:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: raw 
  working_space:
    path: 'NO-WS'

simple-2:
  source_location: '/Users/cwi/VWE/PAV'
  run:
    cmd: 'hw.bash'
    scheduler: moab 
  build:
    build_before_run_flag: True
  working_space:
    path: './tmpws'
